name: Go

on:
  workflow_dispatch:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20' ]

    steps:
      - uses: actions/checkout@v4


      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Initial
        run: go mod init ${{ github.repository }}

      - name: Install dependencies
        run: go get . > hello-2.o

      - name: Building Go
        run: go build .

      - name: Check Directory and Files
        run: ls

       


      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-TestResults-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json

      - uses: AutoModality/action-clean@v1
      - run: echo Hello World
