name: Go

on:
  workflow_dispatch:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20' ]

    steps:
      - uses: actions/checkout@v4


      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build > BuildRes


      - name: Test with Go
        run: go build > BuildResults-${{ matrix.go-version }}
       
       


      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-BuildResults-${{ matrix.go-version }}
          path: BuildResults-${{ matrix.go-version }}
